import { MuseumRoom } from "../types";

export const animalKingdom: MuseumRoom = {
  id: "animal-kingdom",
  name: "Animal Kingdom",
  emoji: "🦁",
  discoveries: [
    {
      id: "elephant",
      title: "Elephant",
      emoji: "🐘",
      fact: "Elephants are the largest land animals, and their trunks are amazing tools with about 40,000 muscles — strong enough to lift a tree, gentle enough to pick up a single peanut.",
      factSimple: "An elephant's trunk has 40,000 muscles!",
      more: "Elephants talk to each other with rumbles too deep for human ears, which travel through the ground for kilometers. They also remember friends and places for decades, and comfort each other when sad.",
      relatedTo: ["blue-whale"],
    },
    {
      id: "cheetah",
      title: "Cheetah",
      emoji: "🐆",
      fact: "The cheetah is the fastest runner on Earth, going from standing still to highway speed in three seconds — but only for a short sprint before it must rest.",
      factSimple: "Cheetahs are the fastest runners in the world.",
      more: "A cheetah's tail works like a boat's rudder, helping it steer during sharp turns. The black 'tear marks' under its eyes work like a footballer's face paint, cutting the sun's glare.",
      relatedTo: ["wolf"],
    },
    {
      id: "honeybee",
      title: "Honeybee",
      emoji: "🐝",
      fact: "Honeybees tell each other where flowers are by dancing — a waggle dance whose direction and length are a map their sisters can follow.",
      factSimple: "Bees dance to tell each other where flowers are.",
      more: "One bee makes only about a twelfth of a teaspoon of honey in her whole life — a jar of honey is the work of thousands of bees visiting millions of flowers. Bees also help grow a third of the food we eat by carrying pollen.",
      relatedTo: ["ant", "hummingbird"],
    },
    {
      id: "owl",
      title: "Owl",
      emoji: "🦉",
      fact: "Owls fly almost silently thanks to feathers with soft, comb-like edges — and they can turn their heads three-quarters of the way around to look behind them.",
      factSimple: "Owls fly silently and can look behind themselves.",
      more: "Owls can't move their eyes in their sockets — that's why they turn their heads so far. Their ears are at different heights, letting them pinpoint a mouse rustling under leaves in complete darkness.",
      relatedTo: ["dolphin", "birds-dinos"],
    },
    {
      id: "penguin",
      title: "Penguin",
      emoji: "🐧",
      fact: "Penguins are birds that traded flying for swimming — underwater they zoom like torpedoes. Emperor penguin dads balance the egg on their feet through the freezing Antarctic winter.",
      factSimple: "Penguin dads keep the egg warm on their feet.",
      more: "Penguins huddle in groups of thousands to stay warm, taking turns standing on the cold, windy outside. They also 'fly' out of the water, leaping onto ice like popping corks.",
      relatedTo: ["seahorse", "desert"],
    },
    {
      id: "chameleon",
      title: "Chameleon",
      emoji: "🦎",
      fact: "A chameleon's eyes move separately, so it can watch two directions at once — and its tongue shoots out faster than a race car accelerates, sometimes twice as long as its body.",
      factSimple: "A chameleon's tongue is longer than its body!",
      more: "Chameleons don't mainly change color to hide — they change with mood and temperature, like wearing their feelings. A calm chameleon might be green; an excited one flashes stripes and spots.",
      relatedTo: ["octopus"],
    },
    {
      id: "ant",
      title: "Ant",
      emoji: "🐜",
      fact: "An ant can carry things 50 times heavier than itself — like a kid lifting a car. Ants leave invisible smell trails so their nest-mates can find the food they discovered.",
      factSimple: "Ants can carry 50 times their own weight.",
      more: "An ant colony works like one big brain: no ant is in charge, not even the queen — she just lays eggs. Some ants farm mushrooms underground, and others keep herds of tiny insects like cows.",
      relatedTo: ["honeybee", "soil"],
    },
    {
      id: "sloth",
      title: "Sloth",
      emoji: "🦥",
      fact: "Sloths move so slowly that tiny green algae grow in their fur — which actually helps them hide among the leaves. Everything about them is slow, even digesting one leaf can take a month.",
      factSimple: "Sloths are so slow that plants grow on them!",
      more: "Being slow is the sloth's superpower: eagles hunting for movement simply don't notice them. Surprisingly, sloths are strong swimmers — three times faster in water than on land.",
    },
    {
      id: "hummingbird",
      title: "Hummingbird",
      emoji: "🌺",
      fact: "Hummingbirds are the only birds that can fly backwards. Their wings beat about 50 times per second — so fast they hum, which is how they got their name.",
      factSimple: "Hummingbirds can fly backwards!",
      more: "A hummingbird's heart can beat over 1,200 times a minute, and it must drink nectar from hundreds of flowers a day to keep going. At night, some enter a deep sleep called torpor — almost like hibernating until morning.",
      relatedTo: ["honeybee", "birds-dinos"],
    },
    {
      id: "wolf",
      title: "Wolf",
      emoji: "🐺",
      fact: "Wolves live in family packs that hunt, play, and raise pups together. A wolf's howl can be heard 10 kilometers away — it's how the family calls 'where are you?' across the forest.",
      factSimple: "Wolves howl to talk to their family far away.",
      more: "Every dog on Earth — from a chihuahua to a great dane — is descended from wolves that made friends with humans more than 15,000 years ago. Wolf packs are usually just a mom, a dad, and their kids.",
      relatedTo: ["cheetah"],
    },
  ],
};
