import { MuseumRoom } from "../types";

export const dinosaurHall: MuseumRoom = {
  id: "dinosaur-hall",
  name: "Dinosaur Hall",
  emoji: "🦕",
  discoveries: [
    {
      id: "trex",
      title: "Tyrannosaurus Rex",
      emoji: "🦖",
      fact: "T. rex had teeth the size of bananas and a bite three times stronger than a lion's — but its arms were so short it couldn't clap.",
      factSimple: "T. rex had teeth as big as bananas!",
      more: "Scientists think T. rex could smell better than almost any animal of its time, sniffing out food from kilometers away. And here's a surprise: T. rex lived closer in time to you than to Stegosaurus!",
      relatedTo: ["fossils", "birds-dinos"],
    },
    {
      id: "triceratops",
      title: "Triceratops",
      emoji: "🛡️",
      fact: "Triceratops had three horns and a giant bony frill to protect its neck — like wearing a built-in shield. It was a plant-eater that lived at the same time as T. rex.",
      factSimple: "Triceratops had three horns and a neck shield.",
      more: "A Triceratops skull could be 2 meters long — as long as a bed! It had up to 800 tiny teeth arranged in stacks, perfect for slicing tough plants.",
      relatedTo: ["trex"],
    },
    {
      id: "velociraptor",
      title: "Velociraptor",
      emoji: "🦃",
      fact: "Real velociraptors were only the size of a turkey — and they were covered in feathers! They were clever, fast hunters with a special curved claw on each foot.",
      factSimple: "Velociraptors were small, feathery, and fast.",
      more: "The movies made velociraptors big and scaly, but fossils show feather bumps on their arm bones. They couldn't fly — their feathers were probably for warmth and showing off.",
      relatedTo: ["birds-dinos"],
    },
    {
      id: "fossils",
      title: "Fossils",
      emoji: "🦴",
      fact: "A fossil is a message from millions of years ago — bones, footprints, or even skin prints that slowly turned to stone while buried in mud and sand.",
      factSimple: "Fossils are ancient bones and footprints turned to stone.",
      more: "It takes at least 10,000 years to make a fossil, and most creatures never become one — that's why every fossil is a treasure. Fossil hunters called paleontologists use brushes, not shovels, for the delicate work.",
      relatedTo: ["mountains", "great-white"],
    },
    {
      id: "brachiosaurus",
      title: "Brachiosaurus",
      emoji: "🦕",
      fact: "Brachiosaurus held its head as high as a four-story building, munching leaves no other dinosaur could reach. It needed to eat about 400 kilograms of plants every day.",
      factSimple: "Brachiosaurus was as tall as a four-story building.",
      more: "For a long time, people thought giant dinosaurs like this lived in lakes because they seemed too heavy to walk. Now we know their bones had air pockets, like birds' bones, making them lighter than they looked.",
      relatedTo: ["birds-dinos"],
    },
    {
      id: "stegosaurus",
      title: "Stegosaurus",
      emoji: "🦔",
      fact: "Stegosaurus wore a row of big bony plates down its back and swung a spiked tail for defense — but its brain was only the size of a walnut.",
      factSimple: "Stegosaurus had back plates and a spiky tail.",
      more: "Scientists still debate what the plates were for: maybe armor, maybe soaking up morning sun like solar panels, or maybe for showing off to other Stegosauruses. The spiky tail even has a name — the thagomizer.",
      relatedTo: ["trex"],
    },
    {
      id: "pterosaur",
      title: "Pterosaurs",
      emoji: "🦅",
      fact: "Pterosaurs were flying reptiles that ruled the skies while dinosaurs ruled the land. The biggest, Quetzalcoatlus, was as tall as a giraffe and flew like a small airplane.",
      factSimple: "Pterosaurs were flying reptiles as big as giraffes.",
      more: "Pterosaurs weren't actually dinosaurs — they were flying cousins of dinosaurs. Their wings were made of skin stretched from one super-long finger down to their legs.",
      relatedTo: ["birds-dinos"],
    },
    {
      id: "asteroid",
      title: "The Great Asteroid",
      emoji: "💥",
      fact: "About 66 million years ago, a rock from space the size of a mountain crashed into Earth. It changed the weather so much that most dinosaurs disappeared.",
      factSimple: "A giant space rock ended the time of the dinosaurs.",
      more: "The crater it left is 180 km wide, hiding under Mexico. Dust from the crash blocked the Sun for years. But some small animals survived — including little furry mammals, whose great-great-great… grandchildren include us.",
      relatedTo: ["comet", "birds-dinos"],
    },
    {
      id: "dino-eggs",
      title: "Dinosaur Eggs",
      emoji: "🥚",
      fact: "All dinosaurs hatched from eggs — even the giants. The biggest dinosaur eggs found are about the size of a basketball; giant dinosaurs started life tinier than you!",
      factSimple: "Even the biggest dinosaurs hatched from eggs.",
      more: "Some fossil nests show dinosaur parents sitting on their eggs to keep them warm, just like birds do today. Baby dinosaur fossils are extra rare because tiny bones are so fragile.",
      relatedTo: ["fossils", "birds-dinos"],
    },
    {
      id: "birds-dinos",
      title: "Birds ARE Dinosaurs",
      emoji: "🐦",
      fact: "Dinosaurs never completely disappeared: birds are living dinosaurs, the direct descendants of small feathered hunters like Velociraptor's family.",
      factSimple: "Birds are living dinosaurs!",
      more: "So every pigeon, chicken, and hummingbird you see is a dinosaur. Scientists can even see dinosaur features in bird skeletons — a chicken's wishbone is the same bone T. rex had in its chest.",
      relatedTo: ["velociraptor", "trex", "hummingbird"],
    },
  ],
};
