import { MuseumRoom } from "../types";

export const earthLab: MuseumRoom = {
  id: "earth-lab",
  name: "Earth Lab",
  emoji: "🌍",
  discoveries: [
    {
      id: "volcano",
      title: "Volcano",
      emoji: "🌋",
      fact: "Volcanoes are windows into the Earth's fiery inside. Melted rock called magma pushes up from deep below — and once it bursts out, it gets a new name: lava.",
      factSimple: "Volcanoes let melted rock from inside the Earth escape.",
      more: "There are volcanoes under the sea too — in fact, most of Earth's volcanoes are underwater. The Hawaiian islands are the tops of giant volcanoes that grew from the ocean floor, one eruption at a time.",
      relatedTo: ["earthquake", "mountains"],
    },
    {
      id: "earthquake",
      title: "Earthquake",
      emoji: "🫨",
      fact: "The ground you stand on is not one solid shell — it's made of giant puzzle pieces called plates that slowly drift. When two pieces suddenly slip, the ground shakes.",
      factSimple: "Earthquakes happen when giant rock pieces underground slip.",
      more: "The plates move about as fast as your fingernails grow. Millions of years of that slow pushing built the tallest mountains — and it means the map of the world is still slowly changing.",
      relatedTo: ["volcano", "mountains"],
    },
    {
      id: "crystals",
      title: "Crystals",
      emoji: "💎",
      fact: "Crystals grow — not like plants, but atom by atom, stacking up in perfect patterns. A diamond is just carbon that was squeezed deep underground for millions of years.",
      factSimple: "Crystals grow underground, atom by atom.",
      more: "In a cave in Mexico, explorers found crystals as long as buses — so big you could walk on them. Salt and sugar are crystals too: look at them closely and you'll see tiny sparkling shapes.",
      relatedTo: ["caves"],
    },
    {
      id: "rivers",
      title: "Rivers",
      emoji: "🏞️",
      fact: "Rivers are the planet's sculptors. Drop by drop, flowing water carves valleys and canyons — the Grand Canyon was carved by a river over millions of years.",
      factSimple: "Rivers slowly carve valleys and canyons into rock.",
      more: "Every river is part of the water cycle: rain falls on mountains, trickles into streams, joins rivers, and finally returns to the sea — where the Sun lifts it back into clouds to rain again.",
      relatedTo: ["rain", "mountains"],
    },
    {
      id: "mountains",
      title: "Mountains",
      emoji: "🏔️",
      fact: "Mount Everest, the tallest mountain on land, is still growing about half a centimeter every year — because two plates of the Earth are slowly pushing into each other beneath it.",
      factSimple: "Mount Everest is still growing taller!",
      more: "Seashell fossils have been found near Everest's peak. That means the rock at the top of the world was once the bottom of an ancient sea, pushed up over millions of years.",
      relatedTo: ["earthquake", "fossils"],
    },
    {
      id: "caves",
      title: "Caves",
      emoji: "🕳️",
      fact: "Many caves are carved by water dissolving rock over thousands of years. Inside, stone icicles called stalactites hang tight to the ceiling, while stalagmites grow up from the floor.",
      factSimple: "Water slowly carves caves into rock.",
      more: "Here's the trick to remember: stalaCtites hold on to the Ceiling, stalaGmites grow from the Ground. When they finally meet after thousands of years, they form a column.",
      relatedTo: ["crystals", "rivers"],
    },
    {
      id: "desert",
      title: "Desert",
      emoji: "🏜️",
      fact: "A desert isn't defined by heat — it's any place that gets almost no rain. The biggest desert on Earth is actually Antarctica, the frozen continent.",
      factSimple: "The biggest desert on Earth is icy Antarctica!",
      more: "Deserts can be scorching by day and freezing by night, because there are few clouds to hold the warmth in. Desert plants like cactuses store water in their thick bodies to survive between rare rains.",
      relatedTo: ["fog", "glacier"],
    },
    {
      id: "glacier",
      title: "Glacier",
      emoji: "🧊",
      fact: "Glaciers are rivers of ice that flow so slowly you can't see them move — yet they are powerful enough to grind whole valleys out of solid rock.",
      factSimple: "A glacier is a slow river of ice.",
      more: "Glacier ice can be tens of thousands of years old. Scientists drill deep ice cores and read them like history books — each layer holds tiny bubbles of ancient air from when that snow fell.",
      relatedTo: ["snowflake", "rivers"],
    },
    {
      id: "geyser",
      title: "Geyser",
      emoji: "⛲",
      fact: "A geyser is a natural fountain: underground water heated by hot volcanic rock builds up pressure until it blasts boiling water high into the sky.",
      factSimple: "Geysers shoot hot water up from underground.",
      more: "The most famous geyser, Old Faithful in Yellowstone, erupts about every 90 minutes and has been doing so for as long as anyone has watched. Some geysers shoot water higher than a 30-story building.",
      relatedTo: ["volcano"],
    },
    {
      id: "soil",
      title: "Soil & Earthworms",
      emoji: "🪱",
      fact: "A single handful of healthy soil contains more living things than there are people on Earth. Earthworms are its gardeners — their tunnels let air and water reach plant roots.",
      factSimple: "One handful of soil holds billions of tiny living things.",
      more: "Earthworms eat fallen leaves and turn them back into food for plants. Charles Darwin, the famous scientist, spent 39 years studying earthworms and called them some of the most important animals in the world.",
      relatedTo: ["ant"],
    },
  ],
};
