import { MuseumRoom } from "../types";

export const humanBody: MuseumRoom = {
  id: "human-body",
  name: "Human Body Hall",
  emoji: "💪",
  discoveries: [
    {
      id: "heart",
      title: "Your Heart",
      emoji: "❤️",
      fact: "Your heart is a muscle about the size of your fist, and it beats around 100,000 times every single day — even while you sleep.",
      factSimple: "Your heart beats 100,000 times a day!",
      more: "In one day, your heart pumps enough blood to fill a bathtub. Squeeze a tennis ball hard — that's about how hard your heart works with every beat, all day, every day, without ever taking a break.",
      relatedTo: ["blue-whale", "blood"],
    },
    {
      id: "brain",
      title: "Your Brain",
      emoji: "🧠",
      fact: "Your brain has about 86 billion tiny cells called neurons, sending messages to each other faster than race cars — that's how you think, remember, and imagine.",
      factSimple: "Your brain has 86 billion tiny thinking cells.",
      more: "Your brain uses about a fifth of all your body's energy, even though it never moves a muscle. And it's busiest while you sleep — sorting today's memories like a librarian shelving books at night.",
      relatedTo: ["sleep", "octopus"],
    },
    {
      id: "bones",
      title: "Bones",
      emoji: "🦴",
      fact: "You were born with about 300 bones, but adults have only 206 — because some of your bones slowly grow together as you get bigger.",
      factSimple: "Kids have more bones than grown-ups!",
      more: "Bones are alive and always rebuilding themselves — if one breaks, it can heal stronger than before. The smallest bone in your body lives inside your ear and is smaller than a grain of rice.",
      relatedTo: ["fossils"],
    },
    {
      id: "blood",
      title: "Blood",
      emoji: "🩸",
      fact: "Your blood is a delivery service: red cells carry oxygen to every corner of your body through tubes that, laid end to end, would wrap around the Earth twice.",
      factSimple: "Your blood tubes could wrap around the Earth twice!",
      more: "A single drop of blood holds millions of red cells, and each one makes a full trip around your body in about a minute. White blood cells are your body's knights, hunting down germs.",
      relatedTo: ["heart", "germs"],
    },
    {
      id: "stomach",
      title: "Your Stomach",
      emoji: "🍎",
      fact: "Your stomach uses acid strong enough to dissolve metal to break down food — and it makes a new slimy lining every few days so it doesn't digest itself.",
      factSimple: "Your stomach acid is strong enough to melt metal!",
      more: "The rumble of a hungry tummy is really your stomach and intestines squeezing air around — the sound even has a fancy name: borborygmus. Food takes about 6 hours to pass through your stomach.",
    },
    {
      id: "lungs",
      title: "Lungs",
      emoji: "🌬️",
      fact: "You take about 20,000 breaths a day. Spread flat, the inside of your lungs would cover half a tennis court — all folded neatly inside your chest.",
      factSimple: "You breathe 20,000 times every day.",
      more: "Your left lung is a little smaller than your right one, to make room for your heart. When you exercise, your lungs and heart team up, working twice as fast to feed your muscles oxygen.",
      relatedTo: ["heart", "wind"],
    },
    {
      id: "skin",
      title: "Skin",
      emoji: "🖐️",
      fact: "Skin is your body's biggest organ — a stretchy, waterproof suit of armor that completely renews itself about every month.",
      factSimple: "Your skin is your body's biggest organ.",
      more: "You shed about 40,000 tiny skin flakes every minute — much of household dust is actually old skin! Your fingertips are so sensitive they can feel a bump smaller than a grain of sand.",
      relatedTo: ["dust"],
    },
    {
      id: "sneeze",
      title: "Sneezes",
      emoji: "🤧",
      fact: "A sneeze blasts air out of your nose at up to 160 kilometers per hour — faster than a car on the highway. It's your body's way of ejecting dust and germs.",
      factSimple: "A sneeze is faster than a car!",
      more: "You can't sneeze with your eyes open — your body closes them automatically. Bright sunlight makes some people sneeze; scientists call it the 'photic sneeze reflex' and it runs in families.",
      relatedTo: ["germs", "dust"],
    },
    {
      id: "sleep",
      title: "Sleep & Dreams",
      emoji: "😴",
      fact: "While you sleep, your brain replays the day and stores what you learned — which is why a good night's sleep actually makes you smarter.",
      factSimple: "Sleeping helps your brain remember what you learned.",
      more: "Everyone dreams several times a night, even people who say they never do — they just forget. Kids your age need about 10 hours of sleep because growing happens mostly at night, when your body releases growth hormone.",
      relatedTo: ["brain", "dolphin"],
    },
    {
      id: "taste",
      title: "Taste Buds",
      emoji: "👅",
      fact: "Your tongue has about 10,000 taste buds, and they're replaced every two weeks. But smell does most of the work — that's why food is boring when your nose is blocked.",
      factSimple: "You have 10,000 taste buds on your tongue!",
      more: "Try holding your nose while eating a jelly bean — you'll barely taste it until you let go. Butterflies taste with their feet, and catfish are covered in taste buds from head to tail!",
      relatedTo: ["honeybee"],
    },
  ],
};
