import { MuseumRoom } from "../types";

export const inventorsWorkshop: MuseumRoom = {
  id: "inventors-workshop",
  name: "Inventors' Workshop",
  emoji: "💡",
  discoveries: [
    {
      id: "wheel",
      title: "The Wheel",
      emoji: "⚙️",
      fact: "The wheel was invented over 5,000 years ago — but here's the surprise: the first wheels weren't for carts. They were for making pottery!",
      factSimple: "The first wheels were for making pots, not carts.",
      more: "It took hundreds of years before someone thought to turn the potter's wheel sideways and put it under a cart. Some of the best ideas are just old ideas turned a new way.",
    },
    {
      id: "paper",
      title: "Paper",
      emoji: "📜",
      fact: "Paper was invented in China about 2,000 years ago, made from mashed-up tree bark and old rags. For centuries it was a carefully guarded secret.",
      factSimple: "Paper was invented in China 2,000 years ago.",
      more: "Before paper, people wrote on clay tablets, animal skins, and papyrus reeds. A single tree can make about 8,000 sheets of paper — one more reason to recycle!",
      relatedTo: ["writing"],
    },
    {
      id: "telescope",
      title: "The Telescope",
      emoji: "🔭",
      fact: "When Galileo pointed the newly invented telescope at the sky in 1609, he discovered moons circling Jupiter — proof that not everything orbits the Earth.",
      factSimple: "Telescopes let us see moons around other planets.",
      more: "Today's biggest telescopes don't even use eyes — they collect light with mirrors as big as swimming pools, and space telescopes send us photos of galaxies whose light left them billions of years ago.",
      relatedTo: ["jupiter", "stars", "microscope"],
    },
    {
      id: "steam-train",
      title: "Steam Trains",
      emoji: "🚂",
      fact: "Two hundred years ago, steam trains were the fastest things humans had ever built. Some people worried that going faster than a horse might make passengers ill!",
      factSimple: "Steam trains were once the fastest things on Earth.",
      more: "A steam engine works like a giant kettle: burning coal boils water, and the pushing steam drives the wheels. Trains shrank journeys that took weeks down to days, and the world suddenly felt smaller.",
    },
    {
      id: "lightbulb",
      title: "The Lightbulb",
      emoji: "💡",
      fact: "Thomas Edison's team tested thousands of materials before finding a lightbulb filament that worked. Edison said he never failed — he just found ways that didn't work.",
      factSimple: "It took thousands of tries to invent the lightbulb.",
      more: "Before electric light, people mostly went to bed when it got dark, and candles caused many house fires. One of the first things kids did under electric light? Read more books at night.",
      relatedTo: ["lightning"],
    },
    {
      id: "telephone",
      title: "The Telephone",
      emoji: "📞",
      fact: "The first telephone call, in 1876, was Alexander Graham Bell calling his assistant in the next room: 'Mr. Watson, come here!' Sound had traveled through a wire for the first time.",
      factSimple: "The first phone call was to the next room!",
      more: "Early phones had no numbers — you asked a human operator to connect you. Your voice travels as invisible waves; a phone turns sound into electricity and back into sound at the other end.",
      relatedTo: ["computer"],
    },
    {
      id: "airplane",
      title: "The Airplane",
      emoji: "✈️",
      fact: "The Wright brothers' first flight in 1903 lasted just 12 seconds — shorter than it takes you to read this fact. Only 66 years later, humans landed on the Moon.",
      factSimple: "The first airplane flight lasted only 12 seconds.",
      more: "Wilbur and Orville Wright ran a bicycle shop and taught themselves everything by testing wings in a homemade wind tunnel. Birds were their teachers — they studied how buzzards twist their wingtips to steer.",
      relatedTo: ["moon", "pterosaur", "hummingbird"],
    },
    {
      id: "computer",
      title: "Computers",
      emoji: "💻",
      fact: "The first computers were as big as whole rooms and slower than today's cheapest watch. One of the very first programmers was a woman named Ada Lovelace — in the 1840s!",
      factSimple: "The first computers filled a whole room.",
      more: "Ada Lovelace wrote programs for a computer that hadn't even been built yet, and imagined machines making music one day. The phone in your house is millions of times faster than the room-sized computers that guided astronauts to the Moon.",
      relatedTo: ["robot", "astronaut"],
    },
    {
      id: "robot",
      title: "Robots",
      emoji: "🤖",
      fact: "Robots today build cars, explore volcanoes, vacuum floors, and drive around Mars. The word 'robot' comes from a play written over 100 years ago.",
      factSimple: "Robots explore Mars and volcanoes for us.",
      more: "The hardest things for robots are the easiest for you: walking on bumpy ground, folding laundry, telling a cat from a dog. Your brain makes these look easy — they're not!",
      relatedTo: ["mars", "computer"],
    },
    {
      id: "velcro",
      title: "Velcro",
      emoji: "🌿",
      fact: "Velcro was invented after a Swiss engineer went hiking and wondered why prickly burrs stuck to his dog's fur. Under a microscope, he found thousands of tiny hooks.",
      factSimple: "Velcro was copied from prickly plants!",
      more: "Copying nature's ideas is called biomimicry: bullet trains are shaped like kingfisher beaks, swimsuits copy sharkskin, and sticky gecko feet inspired new tapes. Nature has been inventing far longer than we have.",
      relatedTo: ["great-white", "microscope"],
    },
  ],
};
