import { MuseumRoom } from "../types";

export const longAgoHall: MuseumRoom = {
  id: "long-ago-hall",
  name: "Long Ago Hall",
  emoji: "🏺",
  discoveries: [
    {
      id: "pyramids",
      title: "The Pyramids",
      emoji: "🔺",
      fact: "The Great Pyramid of Egypt was built 4,500 years ago from over 2 million stone blocks — and it was the tallest building in the world for nearly 4,000 years.",
      factSimple: "The Great Pyramid was the world's tallest building for 4,000 years.",
      more: "Each block weighs about as much as a car, and workers moved them without trucks or cranes — historians think they used sleds, ramps, and wet sand to slide the stones. The pyramid's corners point almost perfectly north, south, east, and west.",
      relatedTo: ["mummies"],
    },
    {
      id: "mummies",
      title: "Mummies",
      emoji: "🇪🇬",
      fact: "Ancient Egyptians preserved their kings and queens as mummies, wrapped in hundreds of meters of linen, so they could journey to the next world.",
      factSimple: "Mummies were wrapped in hundreds of meters of cloth.",
      more: "Egyptians mummified cats too — millions of them — as gifts to the cat goddess Bastet. Tutankhamun's tomb lay hidden for 3,000 years until 1922, still filled with golden treasure.",
      relatedTo: ["pyramids", "writing"],
    },
    {
      id: "knights",
      title: "Knights",
      emoji: "⚔️",
      fact: "A knight's armor weighed about 25 kilograms — as much as a seven-year-old! Yet a trained knight could still run, climb, and even do cartwheels in it.",
      factSimple: "A knight's armor weighed as much as a kid.",
      more: "Boys started training at age 7 as pages, learning manners and horse-riding before ever touching a sword. The rules knights promised to follow — bravery, honesty, protecting others — were called chivalry.",
      relatedTo: ["castles"],
    },
    {
      id: "castles",
      title: "Castles",
      emoji: "🏰",
      fact: "Castles were fortress-homes with walls up to 6 meters thick. Spiral staircases usually twist clockwise going up — so defenders above had room to swing their swords, and attackers didn't.",
      factSimple: "Castle walls could be 6 meters thick!",
      more: "The moat wasn't always water — some were just deep ditches, and some castles kept smelly kitchen waste in them to discourage swimmers. Cold, dark, and drafty: real castle life was less cozy than the movies.",
      relatedTo: ["knights"],
    },
    {
      id: "vikings",
      title: "Vikings",
      emoji: "🛶",
      fact: "Vikings were master sailors who reached North America 500 years before Columbus — navigating by sun, stars, birds, and even the color of the sea.",
      factSimple: "Vikings sailed to America 1,000 years ago.",
      more: "Viking ships were so light and clever they could sail up shallow rivers and even be carried overland. And no, they didn't really wear horned helmets — that was invented for an opera costume!",
      relatedTo: ["stars", "sea-turtle"],
    },
    {
      id: "cave-paintings",
      title: "Cave Paintings",
      emoji: "🖌️",
      fact: "Deep in caves, people painted horses, bison, and handprints more than 30,000 years ago — the oldest art on Earth, made by torchlight with crushed rock and charcoal.",
      factSimple: "The oldest paintings are 30,000 years old.",
      more: "Many handprints were made by blowing paint around a hand like a stencil — and some are small enough to be children's hands. Kids your age left their mark on cave walls 30,000 years ago.",
      relatedTo: ["writing", "caves"],
    },
    {
      id: "colosseum",
      title: "The Colosseum",
      emoji: "🏛️",
      fact: "Rome's Colosseum held 50,000 people 2,000 years ago and had a canvas roof that sailors rigged like a giant sail to shade the crowd.",
      factSimple: "The Colosseum held 50,000 people!",
      more: "The arena floor could be flooded to stage pretend sea battles with real ships. Underneath ran a maze of tunnels and elevators that lifted lions and scenery up through trapdoors.",
      relatedTo: ["castles"],
    },
    {
      id: "great-wall",
      title: "The Great Wall",
      emoji: "🧱",
      fact: "The Great Wall of China stretches over 21,000 kilometers, built over 2,000 years to protect against invaders. Sticky rice was mixed into the mortar to make it stronger!",
      factSimple: "The Great Wall is 21,000 kilometers long.",
      more: "Soldiers on the wall sent messages faster than any rider by lighting smoke signals from tower to tower — news could travel hundreds of kilometers in hours. It's a myth that you can see the wall from space, but it's still the longest thing humans ever built.",
      relatedTo: ["pyramids"],
    },
    {
      id: "ancient-ships",
      title: "Ancient Ships",
      emoji: "⛵",
      fact: "Polynesian explorers crossed the huge Pacific Ocean a thousand years ago in double canoes, reading waves, winds, and stars like a map to find tiny islands.",
      factSimple: "Ancient sailors found tiny islands using only stars and waves.",
      more: "They carried plants, chickens, and whole families on voyages of thousands of kilometers — some of the greatest feats of exploration ever. Navigators memorized 'star paths' — which stars rose and set over which islands.",
      relatedTo: ["vikings", "stars"],
    },
    {
      id: "writing",
      title: "The First Writing",
      emoji: "𓂀",
      fact: "Writing was invented about 5,000 years ago — first as little pictures pressed into clay to count sheep and sacks of grain. Shopping lists came before storybooks!",
      factSimple: "The first writing was for counting sheep and grain.",
      more: "Egyptian hieroglyphs stayed a mystery for centuries until the Rosetta Stone was found — the same message written three ways cracked the code. Every letter you're reading right now descends from those ancient picture-signs.",
      relatedTo: ["paper", "cave-paintings"],
    },
  ],
};
