import { MuseumRoom } from "../types";

export const oceanHall: MuseumRoom = {
  id: "ocean-hall",
  name: "Ocean Hall",
  emoji: "🌊",
  discoveries: [
    {
      id: "octopus",
      title: "Octopus",
      emoji: "🐙",
      fact: "Octopuses have three hearts and blue blood. Two hearts pump blood to their gills, and one pumps it to the rest of their body.",
      factSimple: "An octopus has three hearts!",
      more: "When an octopus swims, the heart that serves its body actually stops beating — which is why octopuses prefer to crawl. They can also change color in less than a second to hide, and each of their eight arms can taste what it touches.",
      relatedTo: ["jellyfish", "coral-reef"],
    },
    {
      id: "blue-whale",
      title: "Blue Whale",
      emoji: "🐋",
      fact: "The blue whale is the largest animal that has EVER lived — bigger than any dinosaur. Its heart alone is the size of a small car.",
      factSimple: "The blue whale is the biggest animal ever!",
      more: "A blue whale's tongue can weigh as much as an elephant. Even though they are giants, they eat some of the smallest creatures in the sea: tiny shrimp-like animals called krill — about 4 tonnes of them every day.",
      relatedTo: ["dolphin"],
    },
    {
      id: "anglerfish",
      title: "Anglerfish",
      emoji: "🎣",
      fact: "Deep in the dark ocean, the anglerfish carries its own glowing lantern — a light on a stalk above its mouth that lures curious fish close.",
      factSimple: "The anglerfish has a glowing light to catch fish.",
      more: "The light isn't made by the fish itself, but by billions of glowing bacteria living inside the lure. Where anglerfish live, it is so deep that sunlight never reaches — it is always midnight there.",
      relatedTo: ["deep-sea"],
    },
    {
      id: "coral-reef",
      title: "Coral Reef",
      emoji: "🐠",
      fact: "Coral looks like colorful rock, but it is actually built by millions of tiny animals called polyps. Reefs are home to a quarter of all ocean life.",
      factSimple: "Coral is made by tiny animals, not rocks!",
      more: "The Great Barrier Reef in Australia is so big it can be seen from space. Corals get their bright colors from tiny algae living inside them — the coral gives the algae a home, and the algae make food from sunlight.",
      relatedTo: ["octopus", "sea-turtle"],
    },
    {
      id: "seahorse",
      title: "Seahorse",
      emoji: "🐚",
      image: "/wonders/seahorse.svg",
      fact: "Seahorses are the only fish that swim standing up — and it's the seahorse dads, not the moms, who carry the babies until they hatch.",
      factSimple: "Seahorse dads carry the babies!",
      more: "A seahorse holds onto seagrass with its curly tail so currents don't sweep it away. Its eyes can look in two different directions at once, one hunting for food while the other watches for danger.",
    },
    {
      id: "great-white",
      title: "Great White Shark",
      emoji: "🦈",
      fact: "Great white sharks can smell a single drop of blood in a swimming pool's worth of water, and they never run out of teeth — new ones keep growing in rows.",
      factSimple: "Sharks grow new teeth their whole life.",
      more: "A shark may go through 30,000 teeth in its lifetime. Sharks are older than trees — they have been swimming in the oceans for more than 400 million years, long before dinosaurs existed.",
      relatedTo: ["fossils"],
    },
    {
      id: "jellyfish",
      title: "Jellyfish",
      emoji: "🎐",
      image: "/wonders/jellyfish.svg",
      fact: "Jellyfish have no brain, no heart, and no bones — they are 95% water — yet they have glided through the oceans for over 500 million years.",
      factSimple: "A jellyfish has no brain and is mostly water!",
      more: "Some jellyfish glow in the dark, and one tiny kind — the 'immortal jellyfish' — can turn itself back into a baby when it gets old, starting life over again. Scientists are still trying to understand how.",
      relatedTo: ["octopus"],
    },
    {
      id: "deep-sea",
      title: "The Deep Sea",
      emoji: "🌑",
      fact: "The deepest place in the ocean, the Mariana Trench, is so deep that Mount Everest could sink into it and still be covered by 2 kilometers of water.",
      factSimple: "The ocean is deeper than the tallest mountain is tall!",
      more: "More people have walked on the Moon than have visited the bottom of the Mariana Trench. Down there the water pushes with the weight of 100 elephants standing on your head — yet strange creatures still live happily in the dark.",
      relatedTo: ["anglerfish", "moon"],
    },
    {
      id: "sea-turtle",
      title: "Sea Turtle",
      emoji: "🐢",
      fact: "Sea turtles travel thousands of kilometers across the ocean, then find their way back to the very same beach where they hatched to lay their own eggs.",
      factSimple: "Sea turtles go back to the beach where they were born.",
      more: "Scientists believe turtles read the Earth's invisible magnetic field like a map. A sea turtle can hold its breath underwater for several hours when it is resting.",
      relatedTo: ["coral-reef"],
    },
    {
      id: "dolphin",
      title: "Dolphin",
      emoji: "🐬",
      fact: "Dolphins call each other by name — each one invents its own special whistle, and friends copy it when they want that dolphin's attention.",
      factSimple: "Every dolphin has its own name-whistle!",
      more: "Dolphins sleep with only half their brain at a time, keeping one eye open so they remember to swim up for air. They also see with sound, sending out clicks and listening to the echoes — like a superpower called echolocation.",
      relatedTo: ["blue-whale", "owl"],
    },
  ],
};
