import { MuseumRoom } from "../types";

export const skyGallery: MuseumRoom = {
  id: "sky-gallery",
  name: "Sky Gallery",
  emoji: "☁️",
  discoveries: [
    {
      id: "rain",
      title: "Rain",
      emoji: "🌧️",
      fact: "Every raindrop begins as water vapor that rises from oceans, lakes, and even puddles, then joins millions of tiny droplets inside a cloud until it grows too heavy to float.",
      factSimple: "Rain is made of tiny cloud droplets joining together.",
      more: "The water in today's rain is ancient — the same water has been raining, flowing to the sea, and rising back into clouds for billions of years. A dinosaur may once have drunk the very water in your glass!",
      relatedTo: ["clouds", "rivers"],
    },
    {
      id: "rainbow",
      title: "Rainbow",
      emoji: "🌈",
      fact: "A rainbow appears when sunlight passes through raindrops, which split the white light into all its hidden colors. No two people ever see exactly the same rainbow.",
      factSimple: "Raindrops split sunlight into colors.",
      more: "A rainbow is actually a full circle — we only see half because the ground gets in the way. From an airplane, you can sometimes see the whole ring. And you can never reach the end of a rainbow, because it moves as you move.",
      relatedTo: ["rain"],
    },
    {
      id: "lightning",
      title: "Lightning",
      emoji: "⚡",
      fact: "A bolt of lightning is five times hotter than the surface of the Sun and flashes for less than a blink. Thunder is the sound of air exploding from that heat.",
      factSimple: "Lightning is hotter than the Sun's surface!",
      more: "Around the world, lightning strikes about 100 times every second. You can tell how far a storm is: count the seconds between the flash and the thunder — every 3 seconds is about 1 kilometer.",
      relatedTo: ["thunder", "sun"],
    },
    {
      id: "clouds",
      title: "Clouds",
      emoji: "☁️",
      fact: "Clouds look light and fluffy, but an average puffy cloud weighs about as much as 100 elephants — the water is just spread into droplets so tiny that they float.",
      factSimple: "A cloud can weigh as much as 100 elephants!",
      more: "Cloud-watchers give clouds names: puffy ones are cumulus, flat blankets are stratus, and wispy feathers high in the sky are cirrus, made of ice. Fog is simply a cloud that is resting on the ground.",
      relatedTo: ["rain", "fog"],
    },
    {
      id: "wind",
      title: "Wind",
      emoji: "💨",
      fact: "Wind is invisible air on the move. The Sun heats some parts of the Earth more than others, and air rushes from cool places to warm places — that rush is the wind.",
      factSimple: "Wind is air moving from cool places to warm places.",
      more: "The fastest wind ever measured on Earth spun inside a tornado at over 480 km/h. On Neptune, winds blow four times faster than that — the windiest place we know of.",
      relatedTo: ["hurricane"],
    },
    {
      id: "snowflake",
      title: "Snowflakes",
      emoji: "❄️",
      fact: "Every snowflake has six sides, and no two are exactly alike — each one's shape tells the story of its journey through the cold clouds.",
      factSimple: "Every snowflake has six sides, and each one is different.",
      more: "A snowflake starts as a speck of dust that water freezes onto. As it tumbles through the cloud, warmer and colder air sculpt its arms — and because no two flakes take the same path, no two look the same.",
      relatedTo: ["clouds", "glacier"],
    },
    {
      id: "hurricane",
      title: "Hurricane",
      emoji: "🌀",
      fact: "A hurricane is a giant spinning storm that can be wider than a whole country — yet its very center, the 'eye', is calm, quiet, and often sunny.",
      factSimple: "The middle of a hurricane is calm and quiet.",
      more: "Hurricanes are born over warm oceans, drinking up heat like fuel. Weather scientists give each one a person's name, going down the alphabet — the first storm of the year might be Alex, the next Bonnie.",
      relatedTo: ["wind", "rain"],
    },
    {
      id: "fog",
      title: "Fog",
      emoji: "🌫️",
      fact: "Fog is a cloud that touches the ground. When you walk through fog, you are actually walking through a cloud.",
      factSimple: "Fog is a cloud on the ground!",
      more: "In some deserts where it almost never rains, beetles survive by standing in the morning fog and letting droplets collect on their backs, then tipping forward so the water rolls right into their mouths.",
      relatedTo: ["clouds", "desert"],
    },
    {
      id: "aurora",
      title: "Northern Lights",
      emoji: "🌌",
      fact: "Near the North and South Poles, the night sky sometimes dances with glowing green and purple ribbons — caused by tiny particles from the Sun crashing into the air high above Earth.",
      factSimple: "The Sun makes glowing lights dance in the polar sky.",
      more: "The aurora happens about 100 km above your head — higher than any airplane flies. Other planets have auroras too: Jupiter's are bigger than our whole planet.",
      relatedTo: ["sun", "jupiter"],
    },
    {
      id: "thunder",
      title: "Thunder",
      emoji: "🌩️",
      fact: "Thunder is the voice of lightning. The bolt heats the air so fast that the air bursts outward with a boom we can hear from kilometers away.",
      factSimple: "Thunder is the sound lightning makes.",
      more: "Light travels almost a million times faster than sound, so you always see the flash before you hear the boom — even though they happen at exactly the same moment.",
      relatedTo: ["lightning"],
    },
  ],
};
