import { MuseumRoom } from "../types";

export const spaceWing: MuseumRoom = {
  id: "space-wing",
  name: "Space Wing",
  emoji: "🚀",
  discoveries: [
    {
      id: "sun",
      title: "The Sun",
      emoji: "☀️",
      fact: "The Sun is a star — our very own — and it's so big that more than a million Earths could fit inside it. Its light takes about 8 minutes to reach us.",
      factSimple: "The Sun is a star, and a million Earths could fit inside it.",
      more: "When you feel sunshine, you're feeling light that left the Sun 8 minutes ago. But that energy was made in the Sun's core long, long before — it can take 100,000 years just to fight its way to the Sun's surface.",
      relatedTo: ["stars", "aurora"],
    },
    {
      id: "moon",
      title: "The Moon",
      emoji: "🌙",
      fact: "The Moon has no light of its own — it shines by reflecting sunlight. Astronauts' footprints are still up there, because the Moon has no wind or rain to wipe them away.",
      factSimple: "Footprints on the Moon never blow away.",
      more: "The Moon is slowly drifting away from Earth — about 4 centimeters every year, the speed your fingernails grow. Long ago it was much closer and would have looked huge in the sky.",
      relatedTo: ["astronaut", "deep-sea"],
    },
    {
      id: "mars",
      title: "Mars",
      emoji: "🔴",
      fact: "Mars is called the Red Planet because its soil is full of rust. It has the tallest volcano in the whole solar system — Olympus Mons, three times taller than Everest.",
      factSimple: "Mars is red because its ground is rusty.",
      more: "Robot rovers drive around Mars right now, taking pictures and studying rocks. A day on Mars is almost the same as ours — just 37 minutes longer — but its year lasts nearly two Earth years.",
      relatedTo: ["volcano", "astronaut"],
    },
    {
      id: "saturn",
      title: "Saturn",
      emoji: "🪐",
      fact: "Saturn's beautiful rings are not solid — they are billions of pieces of ice and rock, some as small as snowflakes and some as big as houses, all circling the planet together.",
      factSimple: "Saturn's rings are made of ice and rocks.",
      more: "Saturn is so light for its size that it would float in a bathtub — if you could find one big enough! It also has more than 100 moons; one of them, Titan, has rivers and lakes of liquid gas.",
      relatedTo: ["jupiter"],
    },
    {
      id: "stars",
      title: "Stars",
      emoji: "⭐",
      fact: "Every star you see at night is a faraway sun. Their light takes so long to reach us that looking at stars is looking back in time.",
      factSimple: "Stars are faraway suns.",
      more: "Some starlight traveling to your eyes tonight left its star before you were born — some even before there were people. There are more stars in the universe than grains of sand on all of Earth's beaches.",
      relatedTo: ["sun", "milky-way"],
    },
    {
      id: "black-hole",
      title: "Black Hole",
      emoji: "⚫",
      fact: "A black hole pulls so strongly that nothing can escape it — not even light. That's why it looks perfectly black.",
      factSimple: "A black hole's pull is so strong even light can't escape.",
      more: "Black holes are born when giant stars collapse. There's a huge one at the center of our galaxy, but don't worry — it's very far away, and black holes don't wander around vacuuming up planets.",
      relatedTo: ["stars", "milky-way"],
    },
    {
      id: "comet",
      title: "Comet",
      emoji: "☄️",
      fact: "A comet is a giant dirty snowball from the edge of the solar system. When it swings near the Sun, it melts a little and grows a glowing tail millions of kilometers long.",
      factSimple: "A comet is a giant snowball with a glowing tail.",
      more: "A comet's tail always points away from the Sun, no matter which way the comet is flying — the Sun's wind blows it back like hair in a breeze. Halley's Comet visits Earth every 76 years.",
      relatedTo: ["sun"],
    },
    {
      id: "astronaut",
      title: "Astronauts",
      emoji: "🧑‍🚀",
      fact: "In space there is almost no gravity pulling on your body, so astronauts float — and they grow about 5 centimeters taller because their spines stretch out.",
      factSimple: "Astronauts float and grow taller in space!",
      more: "Astronauts strap themselves into sleeping bags so they don't drift around while asleep. Their tears can't fall in space — water just clumps into floating balls. And they must exercise two hours a day so their muscles stay strong.",
      relatedTo: ["moon", "mars"],
    },
    {
      id: "milky-way",
      title: "The Milky Way",
      emoji: "🌠",
      fact: "Our Sun and every star you've ever seen all live inside one giant spiral city of stars called the Milky Way — home to hundreds of billions of suns.",
      factSimple: "We live in a giant city of stars called the Milky Way.",
      more: "The whole Milky Way is spinning, and our Sun rides around it like a carousel horse — one full trip takes about 225 million years. The last time we were on this side, dinosaurs were just appearing.",
      relatedTo: ["stars", "black-hole"],
    },
    {
      id: "jupiter",
      title: "Jupiter",
      emoji: "🟠",
      fact: "Jupiter is the giant of our solar system — all the other planets could fit inside it together. Its famous Great Red Spot is a storm bigger than Earth that has raged for centuries.",
      factSimple: "Jupiter is so big all the planets could fit inside it.",
      more: "Jupiter acts like the solar system's bodyguard: its mighty gravity catches many comets and asteroids that might otherwise hit the inner planets — including ours.",
      relatedTo: ["saturn", "hurricane"],
    },
  ],
};
