import { MuseumRoom } from "../types";

export const tinyWorld: MuseumRoom = {
  id: "tiny-world",
  name: "Tiny World",
  emoji: "🔬",
  discoveries: [
    {
      id: "atoms",
      title: "Atoms",
      emoji: "⚛️",
      fact: "Everything — you, water, stars, this screen — is built from atoms so small that a single drop of water holds more atoms than there are stars in the universe.",
      factSimple: "Everything is made of tiny atoms.",
      more: "Atoms are mostly empty space: if an atom were a football stadium, its center would be a pea on the middle line. And your atoms are ancient — the iron in your blood was forged inside exploding stars.",
      relatedTo: ["stars", "crystals"],
    },
    {
      id: "cells",
      title: "Cells",
      emoji: "🧫",
      fact: "You are built from about 37 trillion cells — tiny living factories, each doing its own job: skin cells, brain cells, blood cells, and hundreds more kinds.",
      factSimple: "Your body is made of 37 trillion tiny cells.",
      more: "Every cell came from one single cell dividing again and again. Some cells live for days (stomach), some for months (skin), and some brain cells stay with you your whole life.",
      relatedTo: ["dna", "brain"],
    },
    {
      id: "dna",
      title: "DNA",
      emoji: "🧬",
      fact: "Inside almost every cell is DNA — a twisted-ladder recipe book for building you. Unraveled, the DNA in one cell would stretch 2 meters.",
      factSimple: "DNA is the recipe for building you.",
      more: "You share about half your DNA with a banana, and almost 99% with a chimpanzee — small differences in the recipe make big differences in the dish. All the DNA in your body, joined up, could reach the Sun and back many times.",
      relatedTo: ["cells", "birds-dinos"],
    },
    {
      id: "bacteria",
      title: "Bacteria",
      emoji: "🦠",
      fact: "Trillions of bacteria live on and in you — most of them helpful, busily digesting food and guarding against troublemakers. Your body is their city.",
      factSimple: "Trillions of helpful bacteria live inside you.",
      more: "Bacteria in your tummy help make vitamins and even chat with your brain through chemical messages. Yogurt and cheese are made by friendly bacteria doing delicious work.",
      relatedTo: ["germs", "soil"],
    },
    {
      id: "tardigrade",
      title: "Tardigrades",
      emoji: "🐻‍❄️",
      fact: "Tardigrades — 'water bears' — are nearly invisible animals that can survive boiling, freezing, drying out completely, and even the vacuum of space.",
      factSimple: "Water bears can survive in outer space!",
      more: "When things get tough, a tardigrade curls into a dry ball called a tun and waits — for years if needed — then springs back to life with a drop of water. They live in moss, puddles, and probably your garden.",
      relatedTo: ["astronaut", "soil"],
    },
    {
      id: "plankton",
      title: "Plankton",
      emoji: "🌊",
      fact: "Plankton are tiny drifting sea creatures — and the plant-like ones make about half of the oxygen you breathe. Every second breath comes from the sea!",
      factSimple: "Tiny sea plankton make half the air you breathe.",
      more: "Blue whales, the biggest animals ever, live by eating some of the smallest — krill, which feast on plankton. At night, some plankton glow blue when waves stir them, lighting up beaches like liquid starlight.",
      relatedTo: ["blue-whale", "lungs"],
    },
    {
      id: "mold",
      title: "Mold",
      emoji: "🍞",
      fact: "The fuzzy mold on old bread is a tiny fungus forest. One moldy dish in 1928 changed the world: it led to penicillin, the first antibiotic medicine.",
      factSimple: "A moldy dish led to a medicine that saves lives.",
      more: "Alexander Fleming came back from vacation to find mold killing the germs in his dish — and instead of throwing it away, he asked why. Curiosity about a moldy accident has saved millions of lives.",
      relatedTo: ["bacteria", "germs"],
    },
    {
      id: "dust",
      title: "Dust",
      emoji: "💨",
      fact: "House dust is a mix of skin flakes, clothing fibers, soil, pollen — and even tiny specks of space rock. Thousands of tonnes of cosmic dust fall to Earth every year.",
      factSimple: "Some dust in your house came from space!",
      more: "In every pinch of dust live microscopic dust mites, harmlessly nibbling old skin flakes. And those golden specks floating in a sunbeam? You're watching dust ride the invisible currents of air in your room.",
      relatedTo: ["skin", "comet"],
    },
    {
      id: "microscope",
      title: "The Microscope",
      emoji: "🔬",
      fact: "When the microscope was invented, a Dutch cloth merchant looked at pond water and found it teeming with tiny 'animalcules' — the first human ever to see bacteria.",
      factSimple: "The microscope showed us creatures too small to see.",
      more: "Antonie van Leeuwenhoek ground his own tiny lenses and kept his method secret — for decades he was the only person on Earth who could see the microscopic world. Today's electron microscopes can photograph single atoms.",
      relatedTo: ["telescope", "bacteria", "atoms"],
    },
    {
      id: "germs",
      title: "Germs & Soap",
      emoji: "🧼",
      fact: "Soap doesn't just wash germs away — it actually pulls them apart! Soap molecules grab onto a germ's oily coat and rip it open. Twenty seconds of washing does the trick.",
      factSimple: "Soap pulls germs apart like tiny wrecking balls.",
      more: "Before doctors knew about germs, they didn't wash their hands — a doctor named Semmelweis figured it out in the 1840s, and hand-washing has saved more lives than almost any other discovery.",
      relatedTo: ["bacteria", "mold", "sneeze"],
    },
  ],
};
